[package]
name = "lobster"
version = "0.1.0"
categories = ["data-structures", "simulation"]
edition = "2021"
keywords = ["orderbook", "trading", "finance"]
license = "MIT"
repository = "https://github.com/chariotsofiron/lobster"
rust-version = "1.75"
description = "Limit order book library."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-hash = "2.1.1"

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
proptest = "1.7.0"

[profile.bench]
codegen-units = 1
lto = "thin"

[[bench]]
name = "quantcup"
harness = false

[[bench]]
name = "synthetic"
harness = false

[[bench]]
name = "operations"
harness = false
