//! An order book backed by two vectors.

use core::{cmp::Ordering, fmt};

use crate::{Fill, Order, OrderBook, ReduceError};

/// A straightforward price-time-priority order book backed by vectors.
///
/// Bids and asks are exposed from best to worst. Orders at the same price retain submission order.
#[derive(Clone)]
pub struct VecBook<OrderType: Order> {
    // Ascending by price; the best and oldest order is at the end.
    bids: Vec<OrderType>,
    // Descending by price; the best and oldest order is at the end.
    asks: Vec<OrderType>,
    // Fills generated by the most recent submission.
    fills: Vec<Fill<OrderType>>,
}

impl<OrderType> fmt::Debug for VecBook<OrderType>
where
    OrderType: Order + fmt::Debug,
    Fill<OrderType>: fmt::Debug,
{
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("VecBook")
            .field("bids", &self.bids)
            .field("asks", &self.asks)
            .finish_non_exhaustive()
    }
}

impl<OrderType: Order> Default for VecBook<OrderType> {
    fn default() -> Self {
        Self {
            bids: Vec::new(),
            asks: Vec::new(),
            fills: Vec::new(),
        }
    }
}

impl<OrderType: Order> OrderBook for VecBook<OrderType> {
    type Order = OrderType;

    fn len(&self) -> usize {
        self.bids.len() + self.asks.len()
    }

    fn clear(&mut self) {
        self.bids.clear();
        self.asks.clear();
        self.fills.clear();
    }

    fn bids(&self) -> impl Iterator<Item = &OrderType> {
        self.bids.iter().rev()
    }

    fn asks(&self) -> impl Iterator<Item = &OrderType> {
        self.asks.iter().rev()
    }

    fn submit(&mut self, order: OrderType) -> &[Fill<OrderType>] {
        self.fills.clear();
        if order.is_buy() {
            Self::match_order(order, &mut self.asks, &mut self.bids, &mut self.fills);
        } else {
            Self::match_order(order, &mut self.bids, &mut self.asks, &mut self.fills);
        }
        &self.fills
    }

    fn cancel(&mut self, order_id: &OrderType::OrderId) -> Option<OrderType> {
        if let Some(index) = self.bids.iter().position(|order| order.id() == order_id) {
            return Some(self.bids.remove(index));
        }
        if let Some(index) = self.asks.iter().position(|order| order.id() == order_id) {
            return Some(self.asks.remove(index));
        }
        None
    }

    fn reduce(
        &mut self,
        order_id: &OrderType::OrderId,
        new_quantity: OrderType::Quantity,
    ) -> Result<(), ReduceError> {
        let order = self
            .bids
            .iter_mut()
            .chain(self.asks.iter_mut())
            .find(|order| order.id() == order_id)
            .ok_or(ReduceError::NotFound)?;

        if order.quantity() <= &new_quantity {
            return Err(ReduceError::NotReduced);
        }

        order.set_quantity(new_quantity);
        Ok(())
    }
}

impl<OrderType: Order> VecBook<OrderType> {
    fn match_order(
        mut taker: OrderType,
        makers: &mut Vec<OrderType>,
        resting: &mut Vec<OrderType>,
        fills: &mut Vec<Fill<OrderType>>,
    ) {
        while let Some(maker) = makers.last() {
            if !Self::crosses(&taker, maker) {
                break;
            }

            let taker_quantity = taker.quantity().clone();
            let maker_quantity = maker.quantity().clone();

            match taker_quantity.cmp(&maker_quantity) {
                Ordering::Equal => {
                    let maker = makers.pop().expect("maker was present");
                    fills.push(Fill::Full(maker));
                    return;
                }
                Ordering::Greater => {
                    let maker = makers.pop().expect("maker was present");
                    Self::subtract_quantity(&mut taker, maker_quantity.clone());
                    fills.push(Fill::Full(maker));
                }
                Ordering::Less => {
                    let mut fill = maker.clone();
                    let maker = makers.last_mut().expect("maker was present");
                    Self::subtract_quantity(maker, taker_quantity.clone());
                    fill.set_quantity(taker_quantity);
                    fills.push(Fill::Partial(fill));
                    return;
                }
            }
        }

        Self::insert_resting(resting, taker);
    }

    fn crosses(taker: &OrderType, maker: &OrderType) -> bool {
        if taker.is_buy() {
            taker.price() >= maker.price()
        } else {
            taker.price() <= maker.price()
        }
    }

    fn insert_resting(orders: &mut Vec<OrderType>, order: OrderType) {
        let index = if order.is_buy() {
            orders.partition_point(|probe| probe.price() < order.price())
        } else {
            orders.partition_point(|probe| probe.price() > order.price())
        };
        orders.insert(index, order);
    }

    fn subtract_quantity(order: &mut OrderType, quantity: OrderType::Quantity) {
        let remaining = order.quantity().clone() - quantity;
        order.set_quantity(remaining);
    }
}
